# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSigninTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signinTest(self):
    self.driver.get("http://automationpractice.com/index.php?controller=authentication&back=my-account")
    self.driver.set_window_size(1295, 695)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("bot-akk1@mail.ru")
    self.driver.find_element(By.ID, "passwd").send_keys("2810619")
    self.driver.find_element(By.CSS_SELECTOR, "#SubmitLogin > span").click()
    self.driver.find_element(By.LINK_TEXT, "Sign out").click()
  
